language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode
  - rbx

install:
  - wget 'https://github.com/lloyd/yajl/archive/2.1.0.tar.gz'
  - tar -xvf '2.1.0.tar.gz'
  - cd 'yajl-2.1.0' && ./configure && make && sudo make install
  - sudo ldconfig
  - bundle install --jobs=3 --retry=3

gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx
    - rvm: ruby-head
  fast_finish: true

notifications:
  email: false
